---
- name: ensure systemd
  block:
    - name: ensure carbon-cache service is enabled
      systemd:
        name: "{{ graphite_carbon_cache_service_name }}"
        enabled: true
    - name: ensure carbon-cache service is started
      systemd:
        name: "{{ graphite_carbon_cache_service_name }}"
        state: "started"
    - name: ensure carbon-cache service is restarted
      systemd:
        name: "{{ graphite_carbon_cache_service_name }}"
        state: "restarted"
      when: graphite_carbon_carbon_conf_file_status.changed or
        graphite_carbon_storage_schemas_conf_file_status.changed
  become: true
